name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: 64000
          script: |
            cd cobagithubactions.lignosoftware.com
            rm -r css/ img/ js/
            rm favicon.ico index.html
            git clone https://github.com/abdelhaqf/cobagithubactions
            cd cobagithubactions
            npm install
